//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Satori.AzureDevOps.Tests.WorkItems.SampleFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WorkItemResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkItemResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Satori.AzureDevOps.Tests.WorkItems.SampleFiles.WorkItemResponses", typeof(WorkItemResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;count&quot;: 1,
        ///    &quot;value&quot;: [
        ///        {
        ///            &quot;id&quot;: 3,
        ///            &quot;rev&quot;: 16,
        ///            &quot;fields&quot;: {
        ///                &quot;System.AreaPath&quot;: &quot;Product\\AppArea&quot;,
        ///                &quot;System.TeamProject&quot;: &quot;MyProject&quot;,
        ///                &quot;System.IterationPath&quot;: &quot;CD\\Skunk\\Sprint 2024-02&quot;,
        ///                &quot;System.WorkItemType&quot;: &quot;Product Backlog Item&quot;,
        ///                &quot;System.State&quot;: &quot;New&quot;,
        ///                &quot;System.Reason&quot;: &quot;New backlog item&quot;,
        ///                &quot;System.AssignedTo&quot;: {
        ///                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlockedWorkItem {
            get {
                return ResourceManager.GetString("BlockedWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;count&quot;: 1,
        ///    &quot;value&quot;: [
        ///        {
        ///            &quot;fields&quot;: {
        ///                &quot;Custom.Enhancement&quot;: &quot;&lt;div&gt;Enhance the start up logic to not divide by the number of successfully deployments.  This might cause a division by zero error. &lt;/div&gt;&quot;,
        ///                &quot;Custom.ProjectCode&quot;: &quot;1.2.3 - Skunk Works&quot;,
        ///                &quot;Microsoft.VSTS.CMMI.Blocked&quot;: &quot;No&quot;,
        ///                &quot;Microsoft.VSTS.CMMI.ImpactAssessmentHtml&quot;: &quot;&lt;div&gt;If not fixed we will all be fired and die hungry and alone. &lt;/div&gt;&quot;,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpandedRelations {
            get {
                return ResourceManager.GetString("ExpandedRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;count&quot;: 1,
        ///    &quot;value&quot;: [
        ///        {
        ///            &quot;id&quot;: 2,
        ///            &quot;rev&quot;: 16,
        ///          &quot;fields&quot;: {
        ///            &quot;System.AreaPath&quot;: &quot;Product\\AppArea&quot;,
        ///            &quot;System.TeamProject&quot;: &quot;MyProject&quot;,
        ///            &quot;System.IterationPath&quot;: &quot;CD\\Skunk\\Sprint 2024-02&quot;,
        ///            &quot;System.WorkItemType&quot;: &quot;Product Backlog Item&quot;,
        ///            &quot;System.State&quot;: &quot;New&quot;,
        ///            &quot;System.Reason&quot;: &quot;New backlog item&quot;,
        ///            &quot;System.AssignedTo&quot;: {
        ///              &quot;displayName&quot;: &quot;Timothy Klenke&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingleWorkItem {
            get {
                return ResourceManager.GetString("SingleWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;count&quot;: 5,
        ///    &quot;value&quot;: [
        ///        {
        ///            &quot;id&quot;: 28655,
        ///            &quot;rev&quot;: 6,
        ///            &quot;fields&quot;: {
        ///                &quot;System.AreaPath&quot;: &quot;Product\\AppArea&quot;,
        ///                &quot;System.TeamProject&quot;: &quot;MyProject&quot;,
        ///                &quot;System.IterationPath&quot;: &quot;MyProject\\Skunk\\Sprint 2024-02&quot;,
        ///                &quot;System.WorkItemType&quot;: &quot;Epic&quot;,
        ///                &quot;System.State&quot;: &quot;New&quot;,
        ///                &quot;System.Reason&quot;: &quot;New epic&quot;,
        ///                &quot;System.CreatedDate&quot;: &quot;2023-12-18T21:52:06.91Z&quot;,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SixTypesWorkItems {
            get {
                return ResourceManager.GetString("SixTypesWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;workItemRelations&quot;: [
        ///        {
        ///            &quot;rel&quot;: null,
        ///            &quot;source&quot;: null,
        ///            &quot;target&quot;: {
        ///                &quot;id&quot;: 1,
        ///                &quot;url&quot;: &quot;http://devops.test/Org/_apis/wit/workItems/29228&quot;
        ///            }
        ///        },
        ///        {
        ///            &quot;rel&quot;: &quot;System.LinkTypes.Hierarchy-Forward&quot;,
        ///            &quot;source&quot;: {
        ///                &quot;id&quot;: 1,
        ///                &quot;url&quot;: &quot;http://devops.test/Org/_apis/wit/workItems/29228&quot;
        ///            },
        ///            &quot;target&quot;: {
        ///                &quot;id&quot;: 2,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkItemRelations {
            get {
                return ResourceManager.GetString("WorkItemRelations", resourceCulture);
            }
        }
    }
}
