//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Satori.AzureDevOps.Tests.Processes.SampleFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Responses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Responses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Satori.AzureDevOps.Tests.Processes.SampleFiles.Responses", typeof(Responses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;count&quot;: 2,
        ///  &quot;value&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;9a8ce311-a958-47a9-9475-2a30492b8385&quot;,
        ///      &quot;name&quot;: &quot;ZeroBugProject&quot;,
        ///      &quot;description&quot;: &quot;Project that has is goal to have zero bugs.  Bugs are treated as tasks so that they are addressed before we meet the definition of done-done&quot;,
        ///      &quot;url&quot;: &quot;https://dev.azure.com/KlenkeUniverse/_apis/projects/9a8ce311-a958-47a9-9475-2a30492b8385&quot;,
        ///      &quot;state&quot;: &quot;wellFormed&quot;,
        ///      &quot;revision&quot;: 63,
        ///      &quot;visibility&quot;: &quot;private&quot;,
        ///      &quot;lastUpdateTime&quot;: &quot;2026- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllProjects {
            get {
                return ResourceManager.GetString("AllProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;count&quot;: 10,
        ///  &quot;value&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;System.CurrentProcessTemplateId&quot;,
        ///      &quot;value&quot;: &quot;d0479554-d56d-4a8a-ab22-e8f013adc467&quot;
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;System.OriginalProcessTemplateId&quot;,
        ///      &quot;value&quot;: &quot;d0479554-d56d-4a8a-ab22-e8f013adc467&quot;
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;System.ProcessTemplateType&quot;,
        ///      &quot;value&quot;: &quot;8e2e94ad-d42a-4910-b80a-e7120580a5ed&quot;
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;System.Process Template&quot;,
        ///      &quot;value&quot;: &quot;Scrum&quot;
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;System.Microsoft.Tea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectProperties {
            get {
                return ResourceManager.GetString("ProjectProperties", resourceCulture);
            }
        }
    }
}
